### ISSUE TITLE
[Help] any way to download from Github (Private repo)?

### ISSUE THREAD

**Issue by Blockyheadman** [Lyaaaaaaaaaaaaaaa/Godot_File_Downloader#15]
Helloooo! I wanted to download exe/x86 files from github but I don't really know how to do that or if it's possible. 

_Side Note: Also, I don't understand the Blind Mode feature_

**Comment by Lyaaaaaaaaaaaaaaa** [comment]
Hello, sorry I missed the notification of the message.
I'm not sure what you mean but you can see how to install this plugin into your own projects here https://github.com/Lyaaaaaaaaaaaaaaa/Godot_File_Downloader#how-to-install
Otherwise, to download github files from url you need to open the "raw" version to get the downloadable url of a file.
![image](https://user-images.githubusercontent.com/44974422/178108036-979e98bf-cfb4-48e0-8b2e-44bc1cc5d1c2.png)
![image](https://user-images.githubusercontent.com/44974422/178108115-11488117-1870-4322-8e83-4551872ef6ad.png)
Then you will have the `raw.githubusercontent.com` url which is downloadable from commands and my plugin.

The releases links are also directly usable in the plugin.

**Comment by Blockyheadman** [comment]
So sorry I took a while to respond to this. What I had meant by downloading exe and x86 files is I wanted the files to download from a repository in github. I've tried using raw.githubusercontent.com and looked for a button for the raw contents but because of the file type, it doesn't support that.

**Comment by Lyaaaaaaaaaaaaaaa** [comment]
Hello, do you have a link to the .exe and x86 files you are trying to download? I personally use this project to download files from GitHub. Therefore, it should work for you as well.

**Comment by Blockyheadman** [comment]
Yes. The link I'm not 100% wanting to share though but it would look like this:
https://github.com/Blockyheadman/LauncherApp/blob/main/apps/application.exe
I will note the repo is private if that makes a difference

**Comment by Lyaaaaaaaaaaaaaaa** [comment]
OH! Yes the problem is coming from that. **You can't download from private repositories**. Sorry :-(
